"""
Tests for the ingestion pipeline.

Two layers covered:
  - Error handling (no model loaded — fast tests, no slow marker)
  - Integration end-to-end: ingestion → vectorstore → embeddings → retrieval
    (real model loaded — marked @pytest.mark.slow)

Isolation strategy:
  - Each test gets its own ChromaDB directory via the `tmp_path` fixture.
  - settings.chroma_path is monkeypatched to point at it.
  - get_vectorstore.cache_clear() is called so the cached singleton is rebuilt
    against the new path.
  - The embeddings model is NOT cleared between tests — it's shared via
    @lru_cache to amortize its 30-60s load cost across the whole suite.

The PDF fixture (tests/fixtures/sample.pdf) was generated by
_generate_sample.py in the same folder. See that script if it ever needs
to be regenerated.
"""
from pathlib import Path

import pytest

from app.core import vectorstore as vectorstore_module
from app.core.config import settings
from app.core.exceptions import IngestionError
from app.core.ingestion import IngestionResult, ingest_pdf, ingest_text

PDF_FIXTURE = Path(__file__).parent / "fixtures" / "sample.pdf"


@pytest.fixture
def isolated_vectorstore(tmp_path, monkeypatch):
    """
    Point the vector store at a per-test temporary directory.

    Without this, every test would write to the real ./chroma_db, polluting
    each other and leaving residue on disk. With this, each test starts from
    an empty database and pytest cleans up automatically.

    We must also clear the @lru_cache on get_vectorstore — otherwise the
    factory would return the singleton built on the previous path.
    """
    monkeypatch.setattr(settings, "chroma_path", str(tmp_path / "chroma_db"))
    vectorstore_module.get_vectorstore.cache_clear()
    yield
    # Post-test cleanup: also clear cache so the next test rebuilds cleanly.
    vectorstore_module.get_vectorstore.cache_clear()


# ---------------------------------------------------------------------------
# Error handling tests — no model loaded, fast.
# ---------------------------------------------------------------------------


def test_ingest_text_raises_on_empty_string():
    """Empty text must raise IngestionError with a clear message."""
    with pytest.raises(IngestionError, match="empty"):
        ingest_text("", "empty.txt")


def test_ingest_text_raises_on_whitespace_only():
    """Whitespace-only text must be treated as empty."""
    with pytest.raises(IngestionError, match="empty"):
        ingest_text("   \n\t  ", "blank.txt")


def test_ingest_pdf_raises_on_missing_file():
    """A nonexistent file path must raise IngestionError."""
    with pytest.raises(IngestionError, match="not found"):
        ingest_pdf("/nonexistent/path/to/file.pdf")


# ---------------------------------------------------------------------------
# Integration tests — real model and real Chroma. Marked slow.
# ---------------------------------------------------------------------------


@pytest.mark.slow
def test_ingest_text_creates_chunks_and_returns_result(isolated_vectorstore):
    """
    Happy path: ingesting a non-trivial Italian text produces an
    IngestionResult with at least one chunk and no warnings.
    """
    text = (
        "Il gatto dorme sul divano del salotto. "
        "La pasta al pomodoro è una ricetta italiana. "
        "Roma è la capitale d'Italia."
    )
    result = ingest_text(text, "demo.txt")

    assert isinstance(result, IngestionResult)
    assert result.source == "demo.txt"
    assert result.chunks_created >= 1
    assert result.pages_skipped == 0
    assert result.warnings == []


@pytest.mark.slow
def test_ingest_text_is_idempotent_by_source(isolated_vectorstore):
    """
    Re-ingesting the same source replaces the previous chunks rather than
    appending. After two ingestions, the chunk count for that source
    should equal the count after a single ingestion.
    """
    text = "Il gatto dorme sul divano del salotto."
    source = "demo.txt"

    first = ingest_text(text, source)
    second = ingest_text(text, source)

    # Both calls produce the same number of chunks (delete-then-insert).
    assert first.chunks_created == second.chunks_created

    # And the store now contains exactly that many chunks for this source —
    # not double, which would be the bug we're guarding against.
    vs = vectorstore_module.get_vectorstore()
    stored = vs.get(where={"source": source})
    assert len(stored["ids"]) == second.chunks_created


@pytest.mark.slow
def test_ingestion_enables_semantic_retrieval(isolated_vectorstore):
    """
    End-to-end proof that the pipeline works: after ingesting a few
    semantically-distinct sentences, a similarity query for one topic
    returns the relevant chunk above the irrelevant ones.

    This is the headline test of the file — it validates that ingestion,
    embeddings (with E5 prefixes), and Chroma similarity search all
    cooperate correctly.
    """
    ingest_text(
        "Il gatto domestico dorme tranquillamente sul divano del salotto.",
        "cat.txt",
    )
    ingest_text(
        "La pasta al pomodoro è una ricetta tradizionale italiana.",
        "pasta.txt",
    )
    ingest_text(
        "Roma è la capitale d'Italia, famosa per il Colosseo.",
        "rome.txt",
    )

    vs = vectorstore_module.get_vectorstore()
    results = vs.similarity_search("Dove dorme il gatto?", k=1)

    assert len(results) == 1
    # The top hit should come from the cat document, not pasta or rome.
    assert results[0].metadata["source"] == "cat.txt"


@pytest.mark.slow
def test_ingest_pdf_extracts_text_from_real_pdf(isolated_vectorstore):
    """
    Ingesting a small two-page PDF fixture produces at least one chunk
    with the expected source and page metadata.
    """
    assert PDF_FIXTURE.is_file(), (
        f"Missing fixture: {PDF_FIXTURE}. "
        f"Regenerate it with: python tests/fixtures/_generate_sample.py"
    )

    result = ingest_pdf(str(PDF_FIXTURE))

    assert result.source == "sample.pdf"
    assert result.chunks_created >= 1

    # Verify the chunks carry both 'source' and 'page' metadata, which the
    # API layer will need for citations in Phase 3.
    vs = vectorstore_module.get_vectorstore()
    stored = vs.get(where={"source": "sample.pdf"})
    assert len(stored["ids"]) == result.chunks_created
    # PyPDFLoader populates 'page' (0-indexed); we should have entries from
    # both pages of the fixture.
    pages_seen = {meta["page"] for meta in stored["metadatas"]}
    assert pages_seen == {0, 1}