"""
End-to-end RAG chain.

Composes the building blocks built in earlier modules into a single
question-answering pipeline:

    query → retriever (vectorstore) → context formatting →
        prompt template → LLM → string answer

The chain is built with LCEL (LangChain Expression Language), the modern
declarative composition syntax based on the `|` operator. Each component
exposes a uniform .invoke / .stream / .batch interface, so swapping
implementations (e.g. Ollama → Groq for the LLM) requires no changes to
the chain wiring.

Public API:
  - answer(question) → RAGAnswer  (the function the API layer will call)
  - get_chain()                   (the cached LCEL chain, exposed for tests)

Memory is intentionally NOT implemented here: this module is stateless.
Conversation memory belongs to the API layer (Phase 3), where the notion
of a 'session' lives natively.
"""
from dataclasses import dataclass
from functools import lru_cache
from typing import Any

from langchain_core.documents import Document
from langchain_core.output_parsers import StrOutputParser
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import Runnable, RunnableParallel, RunnablePassthrough

from app.core.config import settings
from app.core.llm import get_llm
from app.core.vectorstore import get_vectorstore


PROMPT_TEMPLATE = """Sei un assistente che risponde a domande basandoti \
esclusivamente sul contesto fornito di seguito. Se il contesto non \
contiene informazioni sufficienti per rispondere, dichiaralo onestamente \
invece di inventare una risposta.

Contesto:
{context}

Domanda: {question}

Risposta:"""


@dataclass
class RAGAnswer:
    """
    Structured result of a RAG query.

    Returned to the API layer so it can build informative responses
    that include citations.

    Fields:
      - answer:  the natural-language response generated by the LLM.
      - sources: one entry per retrieved chunk, with enough metadata
                 for the UI to display citations (filename, page,
                 short text preview).
    """
    answer: str
    sources: list[dict[str, Any]]


def _format_docs_with_sources(docs: list[Document]) -> str:
    """
    Render retrieved chunks into a single string for prompt injection.

    Each chunk is prefixed with a '[Fonte: ...]' header that exposes its
    origin metadata to the LLM. This is what enables the model to produce
    grounded, citable answers (e.g. "secondo report.pdf, pagina 3, ...").

    The 'page' key is present on PDF-derived chunks and absent on
    plain-text ones — we handle both.
    """
    blocks = []
    for doc in docs:
        meta = doc.metadata
        source = meta.get("source", "sconosciuto")
        page = meta.get("page")
        header = f"[Fonte: {source}, pagina {page + 1}]" if page is not None else f"[Fonte: {source}]"
        blocks.append(f"{header}\n{doc.page_content}")
    return "\n\n".join(blocks)


def _docs_to_sources(docs: list[Document]) -> list[dict[str, Any]]:
    """
    Build the user-facing 'sources' list returned alongside the answer.

    Truncates each chunk to a short preview so the API response stays
    compact — the full text is already in the vector store and can be
    fetched separately if needed.
    """
    sources = []
    for doc in docs:
        meta = doc.metadata
        sources.append({
            "source": meta.get("source", "sconosciuto"),
            "page": meta.get("page"),
            "preview": doc.page_content[:200].strip(),
        })
    return sources


@lru_cache(maxsize=1)
def get_chain() -> Runnable:
    """
    Build (once) the LCEL chain that turns a question into an answer.

    Pipeline (read top-to-bottom):
      1. The user's question is passed to two parallel branches:
         - a retriever that fetches the top-k relevant chunks
         - the question itself, untouched (RunnablePassthrough)
      2. The retrieved docs are formatted into a context string with
         source citations.
      3. Context + question fill the prompt template.
      4. The prompt is sent to the configured LLM.
      5. The output parser extracts the plain string from the LLM message.

    Returns a Runnable. We cache it because the underlying components
    (embeddings, LLM, vectorstore) are themselves cached singletons —
    rebuilding the chain on every call would be wasteful even if cheap.
    """
    retriever = get_vectorstore().as_retriever(
        search_kwargs={"k": settings.retrieval_k}
    )
    prompt = ChatPromptTemplate.from_template(PROMPT_TEMPLATE)
    llm = get_llm()

    # The 'context' branch retrieves docs and formats them for the prompt.
    # The 'question' branch passes the question through unchanged.
    # RunnableParallel runs both concurrently and merges them into a dict
    # that matches the prompt's expected input keys.
    return (
        RunnableParallel(
            context=retriever | _format_docs_with_sources,
            question=RunnablePassthrough(),
        )
        | prompt
        | llm
        | StrOutputParser()
    )


def answer(question: str) -> RAGAnswer:
    """
    Answer a question using the RAG pipeline.

    Two-step execution:
      1. Run the retriever standalone to capture the source documents
         (we need them for the response payload, not just for the prompt).
      2. Run the full chain to generate the answer.

    This mild duplication (retriever runs twice, once for sources and once
    inside the chain) is the standard idiom for "answer + citations" with
    LCEL. Optimizing it away would require more complex chain wiring with
    .pick / .assign — not worth the cognitive cost at this scale.

    Returns:
        RAGAnswer with the LLM-generated answer and the source chunks
        used to ground it.
    """
    if not question or not question.strip():
        # Defensive: an empty question would still 'work' (LLM hallucinates)
        # but produces useless output. Fail explicitly.
        raise ValueError("Question must be a non-empty string.")

    retriever = get_vectorstore().as_retriever(
        search_kwargs={"k": settings.retrieval_k}
    )
    retrieved_docs = retriever.invoke(question)
    chain = get_chain()
    answer_text = chain.invoke(question)

    return RAGAnswer(
        answer=answer_text,
        sources=_docs_to_sources(retrieved_docs),
    )